name: Deploy

on:
  push:
    branches:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.13'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Download Build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist

      - name: Deploy to github page
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist